language: swift
osx_image: xcode10.2
cache:
  - bundler
install:
  - bundle install
  - pod install --repo-update

addons:
  sonarcloud:
    organization: spacepandas
    token: $SONAR

jobs:
  include:
    - script: ./tests.sh
      name: Unit Tests
    - script: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml
      name: SwiftLint
