language: swift
osx_image: xcode10.2
cache:
  - bundler
install:
  - bundle install
  - pod install
jobs:
  include:
    - stage: test
      script: bundle exec fastlane test
    - stage: swiftlint
      script: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml 
