language: swift
osx_image: xcode10.1
install:
  - bundle install
  - pod repo update
  - pod install
jobs:
include:
  - stage: test
    script: bundle exec fastlane test
  - stage: swiftlint
    script: bundle exec swiftlint lint --config .swiftlint.yml
