language: swift
osx_image: xcode10.2
cache:
  - bundler
install:
  - bundle install
  - pod install --repo-update
jobs:
  include:
      - script: bundle exec fastlane test
      - script: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml 
        name: "SwiftLint"
