language: swift
osx_image: xcode10.2
cache:
  - bundler
install:
  - bundle install
  - pod install --repo-update

addons:
  sonarcloud:
    organization: spacepandas

jobs:
  include:
    - script: bundle exec fastlane test
      name: Unit Tests
      fork: true
    - script: ./tests.sh
      name: Unit Tests + SonarCloud
      fork: false
    - script: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml
      name: SwiftLint
