language: swift
osx_image: xcode11
cache:
  - bundler
install:
  - bundle install
  - pod install --repo-update

addons:
  sonarcloud:
    organization: spacepandas

jobs:
  include:
    - script: bundle exec fastlane test
      name: Unit Tests
      if: fork = true
    - script: ./tests.sh
      name: Unit Tests + SonarCloud
      if: fork = false
    - script: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml
      name: SwiftLint
    - script: bundle exec fastlane screenshots_limited
      name: UI Test
