language: swift
osx_image: xcode10.2
cache:
  - bundler
install:
  - bundle install
  - pod install --repo-update
jobs:
  include:
    - script: ./tests.sh
      name: Unit Tests
    - script: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml
      name: SwiftLint
