name: Set Up Dependencies
description: Installs required ruby gems and cocoapods
runs-on: macOS-latest

steps:
- name: Checkout
  uses: actions/checkout@v1
  with:
    fetch-depth: 1

- name: Cache Ruby Gems
  uses: actions/cache@v1
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gem-

- name: Cache Cocoapods
  uses: actions/cache@v1
  with:
    path: Pods
    key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-pods-

- name: Install Gem Dependencies
  run: |
    bundle config path vendor/bundle
    bundle install
    
- name: Install CocoaPods Dependencies
  run: pod install --repo-update
