name: Beta

on:
  # push:
  #   tags:
  #   - '*'
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_and_deploy:
    name: Build App and Deploy to Testflight
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Gem Dependencies
      run: bundle install
        
    - name: Install CocoaPods Dependencies
      run: pod install --repo-update

    - name: Run "fastlane beta" Action
      run: bundle exec fastlane beta
