name: CI

on: [push]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Dependencies
      uses: ./.github/actions/dependencies

    - name: Run UnitTests
      run: bundle exec fastlane test

  snapshot_tests:
    name: Snapshot Tests
    runs-on: macOS-latest

    steps:
    - name: Dependencies
      uses: ./.github/actions/dependencies

    - name: Run SnapshotTests
      run: bundle exec fastlane snapshot_test

  swiftlint:
    name: Swiftlint
    runs-on: macOS-latest

    steps:
    - name: Dependencies
      uses: ./.github/actions/dependencies

    - name: Run Swiftlint
      run: Pods/SwiftLint/swiftlint lint --config .swiftlint.yml
