name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Cache SPM artifacts
      uses: actions/cache@v1
      with:
        path: DerivedData/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Gem Dependencies
      run: bundle install

    - name: Run UnitTests
      run: bundle exec fastlane test

  snapshot_tests:
    name: Snapshot Tests
    runs-on: macOS-latest

    steps:
    - name: Cache SPM artifacts
      uses: actions/cache@v1
      with:
        path: DerivedData/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Gem Dependencies
      run: bundle install

    - name: Run SnapshotTests
      run: bundle exec fastlane snapshot_test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Cache SPM artifacts
      uses: actions/cache@v1
      with:
        path: DerivedData/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Checkout
      uses: actions/checkout@v1

    - name: Run SwiftLint Checks
      uses: norio-nomura/action-swiftlint@3.0.1
      with:
        args: --strict
