name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Read CHANGELOG
      id: changelog
      run: |
        echo "::set-output name=body::$(./get-changelog-for-version.sh ${{ github.ref }})"

    - name: Create GitHub Release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.changelog.outputs.body }}
        draft: false
        prerelease: false
